import FINAL_TILE_ASTEROID from '@/assets/final_scoring/FINAL_TILE_ASTEROID.png';
import FINAL_TILE_DEEP_SECTORS from '@/assets/final_scoring/FINAL_TILE_DEEP_SECTORS.png';
import FINAL_TILE_PLANET_TYPES from '@/assets/final_scoring/FINAL_TILE_PLANET_TYPES.png';
import FINAL_TILE_PI_ACADEMY_DISTANCE from '@/assets/final_scoring/FINAL_TILE_PI_ACADEMY_DISTANCE.png';
import FINAL_TILE_FEDERATION_POWER from '@/assets/final_scoring/FINAL_TILE_FEDERATION_POWER.png';
import FINAL_TILE_SECTORS_WITH_BUILDINGS from '@/assets/final_scoring/FINAL_TILE_SECTORS_WITH_BUILDINGS.png';
import FINAL_TILE_MOST_BUILDINGS from '@/assets/final_scoring/FINAL_TILE_MOST_BUILDINGS.png';
import FINAL_TILE_FEDERATION_BUILDINGS from '@/assets/final_scoring/FINAL_TILE_FEDERATION_BUILDINGS.png';
import FINAL_TILE_GAIA_PLANET from '@/assets/final_scoring/FINAL_TILE_GAIA_PLANET.png';

export const FINAL_SCORING_IMAGE_MAP: Record<string, string> = {
  FINAL_TILE_ASTEROID,
  FINAL_TILE_DEEP_SECTORS,
  FINAL_TILE_PLANET_TYPES,
  FINAL_TILE_PI_ACADEMY_DISTANCE,
  FINAL_TILE_FEDERATION_POWER,
  FINAL_TILE_SECTORS_WITH_BUILDINGS,
  FINAL_TILE_MOST_BUILDINGS,
  FINAL_TILE_FEDERATION_BUILDINGS,
  FINAL_TILE_GAIA_PLANET,
};
